### ISSUE TITLE
No Public Interfaces Causes Crash

### ISSUE THREAD

**Issue by SquirrelAssassin** [trondhindenes/armrest#1]
errors out at 
String PublicIpLink = nicObj.properties.ipConfigurations.FirstOrDefault().properties.publicIPAddress.id; 
in util / computeresources.cs when a public ip is disabled on the vm.

**Comment by trondhindenes** [comment]
Thanks! This was fixed a while ago but not pushed to this repo. I'll give it a push

**Comment by trondhindenes** [comment]
Pushed a newer version now, which (among other things) handles missing public ips. Please see the web.config for updated config options!
